version: "3"
services:
  db:
    image: mysql:latest
    container_name: cs560-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - /home/youngseok/workspace/cs560/project:/opt/project